#!/bin/sh

sv up ganache || exit 1
sv up redis-node-bob || exit 1
sv up eth-bob || exit 1
sv up xrp-bob || exit 1

exec ilp-node \
  --ilp_address example.bob \
  --secret_seed 1604966725982139900555208458637022875563691455429373719368053354 \
  --admin_auth_token "$BOB_AUTH" \
  --redis_url redis://127.0.0.1:6381/ \
  --http_bind_address "$BOB_NODE" \
  --settlement_api_bind_address 127.0.0.1:8771 \
  --exchange_rate.provider CoinCap
