#!/bin/sh

exec 2>&1

sv up redis-xrp-charlie || exit 1

export DEBUG="*"
export CONNECTOR_URL="http://localhost:9771"
export REDIS_URI=127.0.0.1:6385
export ENGINE_PORT=3003

exec ilp-settlement-xrp
